### PR TITLE
fix hang when client lacks socket permissions

### LINKED ISSUE #5: Running k3c without root hangs
Im running `sudo ./k3c daemon` but keep missing out sudo on running the `k3c run`, `k3c ps` etc.

It wcould be great UX if k3c running without enough privileges could return an error, rather then hang forever.

### PR DESCRIPTION
**Pull request by dweomer**
Fixes #5

### CODE REVIEW

File: pkg/endpointconn/endpoint.go [hunk 1]
```diff
@@ -18,7 +18,7 @@ func Get(ctx context.Context, endpoint string) (*grpc.ClientConn, error) {
 		return nil, err
 	}
 
-	conn, err := grpc.DialContext(ctx, target, grpc.WithInsecure(), grpc.WithBlock(), grpc.WithContextDialer(dialer))
+	conn, err := grpc.DialContext(ctx, target, grpc.WithInsecure(), grpc.WithBlock(), grpc.WithContextDialer(dialer), grpc.FailOnNonTempDialError(true))
```
Comment (dweomer) [inline pkg/endpointconn/endpoint.go]: `grpc.FailOnNonTempDialError` hints gRPC to stop retrying on things that aren't going to fix themselves

**Comment by alexellis** [comment]
I wonder what it was you were building in Aug 2018 when you saw this. 🤔
